config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	
  	resources :articles
  	root 'articles#index'

	resources :categories
	resources :reviews

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category
	has_many :reviews

	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]



	validates_presence_of :title,:body,:category_id,:publish_date,:feature_image_url,:slug
	validate :date_checker
	mount_uploader :feature_image_url, FeatureImageUrlUploader

	def date_checker
		if publish_date > 1.month.from_now
			errors.add(:publish_date,"publish date can't be more then 30days ")
		end
	end

		
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :name,:description
	has_many :articles


end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :article
	belongs_to :user
	validates_presence_of :body,:article_id,:rating

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]


	def index
		@articles = Article.all
	end
	def new
		@article = Article.new
	end
	def create
		@article = Article.new(article_params)
		if @article.publish_date <= Date.today
			@article.is_published = true
		else
			@article.is_published = false
		end
				

		if @article.save
			redirect_to articles_path
		else
			render action: "new"
		end
	end

	def show
 
		@review = Review.new
	end

	def edit

	end

	def update
		if @article.update_attributes (article_params)
			redirect_to articles_path(@article.id)
		else
			render action: "edit"
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end



private

	def article_params

		params[:article].permit(:title,:body,:is_published,:publish_date,:feature_image_url,:category_id,:slug)
	end


	def set_article
			@article = Article.find(params[:id])
	end




end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end
	def create
		@category = Category.new(params[:category].permit(:name,:description))
		if @category.save
			redirect_to categories_path
		else
			render action: "new"
		end
	end

	def show
		@category = Category.find(params[:id])

	end

	def edit
		@category = Category.find(params[:id])

	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes (params[:category].permit(:name,:description))
			redirect_to categories_path(@category.id)
		else
			render action: "edit"
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end





end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


	def index
		@reviews = Review.all
	end
	def show 

		@review = Review.find(params[:id])

	end	

	def create 
		@review = Review.new(params[:review].permit(:body,:article_id,:rating)) 
		if @review.save
			redirect_to article_path(@review.article.id)
		
		end
	end


	def edit
		@review = Review.find(params[:id])
	end

	def update
		@review = Review.find(params[:id])
		if @review.update_attributes (params[:review].permit(:body,:article_id,:rating))
			redirect_to article_path(@review.article.id)
		else
			render action: "edit"
		end
	end

	def destroy
		@review = Review.find(params[:id])
		if @review.destroy 
		redirect_to article_path(@review.article.id)
		end 
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/articles/_form.html.erb
<%=form_for @article do |f|%>
	<%if @article.errors.any?%>
	<h3>These errors prohibited the form </h3>
	<ul>
		<%@article.errors.full_messages.each do |msg|%>
		<li><%=msg%></li>
		<%end%>
	</ul>
	<%end%>


	<label for= "article_category_id"> Category :</label><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

	<label for= "article_title"> Title : </label><br/>
	<%= f.text_field :title %> <br/>
	
    <label for= "article_body "> Body  : </label><br/>
	<%= f.text_area :body%> <br/>

   <label for= "feature_image_url "> Image : </label><br/>
   <%= f.file_field :feature_image_url%> <br/>

  
    <label for= "article_publish_date "> Published date  : </label><br/>
	<%= f.date_field :publish_date, order: [:day, :month, :year]%><br/>

	<%=f.submit %>

	
<%end%>

app/views/articles/edit.html.erb
<h2>Edit Article </h2>
<%= render 'form'%>

app/views/articles/index.html.erb
<div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="display-5"> Listing Articles
            <small><%= @articles.count %></small>
          </h1>


        <% @articles.each do |article| %>  	
          <!-- Blog Post -->
	          <div class="card mb-4">
	          	<%= image_tag(article.feature_image_url, size: "750x300", class: "card-img-top") %>
	            <div class="card-body">
	              <h2 class="card-title"><%= article.title %></h2>
	              <p class="card-text"><%= raw(article.body.truncate(250)) %></p>
	              <%= link_to "Read More", article, class: 'btn btn-primary' %> 
	            </div>
	            <div class="card-footer text-muted">
	              Posted on <%= article.publish_date.strftime("%B %d %Y") %>
	             <%= link_to article.category.name, article.category %>
	            </div>
	          </div>
          <% end %>


          <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
          </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

app/views/articles/new.html.erb
<h2>Add Article</h2>
<%= render 'form'%>

app/views/articles/show.html.erb
  <div class="row">

  	<!-- Post Content Column -->
  	<div class="col-lg-8">

  		<!-- Title -->
  		<h1 class="mt-4"><%= @article.title %></h1>
  		<!-- Author -->
  		<p class="lead">
  			in 
  			<%= link_to @article.category.name, @article.category %>
  		</p>
  		<hr>
  		<!-- Date/Time -->
  		<p>Posted on <%= @article.publish_date.strftime("%B %d %Y %H:%M %p")%></p>
  		<hr>
  		<!-- Preview Image -->
  		<%= image_tag(@article.feature_image_url, size: "900x300", class: "img-fluid rounded") %>
  		<hr>
  		<!-- Post Content -->
  		<p> <%= raw(@article.body) %></p>
  		<hr>
  		<!-- Single Comment -->
  		<% @article.reviews.each do |review| %> 
  		<div class="media mb-4">
  			<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
  			<div class="media-body">
  				<h5 class="mt-0"><%= review.user.try(:email) %></h5>
  				<%= review.body %>
  				<%= review.rating %>
  			</div>
  		</div>
  		<% end %>
  		<!-- Comments Form -->
  		<div class="card my-4">
  			<h5 class="card-header">Leave a Comment:</h5>
  			<div class="card-body">

  				<%= form_for @review do |f| %>

  				<%= f.hidden_field :article_id , value: @article.id %><br/>
  				<div class="form-group">
  					<%= f.text_area :body, class: "form-control" %>
  				</div>

  				<label for ="review_rating"> Rating :</label>
  				<%= f.radio_button :rating,1%>1
  				<%= f.radio_button :rating,2%>2
  				<%= f.radio_button :rating,3%>3
  				<%= f.radio_button :rating,4%>4
  				<%= f.radio_button :rating,5%>5 <br/>
  				<%= f.submit "Add Comment", class: "btn btn-primary" %>
  				<%end%>


  			</div>
  		</div>



  	</div>

  	<!-- Sidebar Widgets Column -->
  	<div class="col-md-4">

  		<!-- Search Widget -->
  		<div class="card my-4">
  			<h5 class="card-header">Search</h5>
  			<div class="card-body">
  				<div class="input-group">
  					<input type="text" class="form-control" placeholder="Search for...">
  					<span class="input-group-btn">
  						<button class="btn btn-secondary" type="button">Go!</button>
  					</span>
  				</div>
  			</div>
  		</div>

  		<!-- Categories Widget -->
  		<div class="card my-4">
  			<h5 class="card-header">Categories</h5>
  			<div class="card-body">
  				<div class="row">
  					<div class="col-lg-6">
  						<ul class="list-unstyled mb-0">
  							<li>
  								<a href="#">Web Design</a>
  							</li>
  							<li>
  								<a href="#">HTML</a>
  							</li>
  							<li>
  								<a href="#">Freebies</a>
  							</li>
  						</ul>
  					</div>
  					<div class="col-lg-6">
  						<ul class="list-unstyled mb-0">
  							<li>
  								<a href="#">JavaScript</a>
  							</li>
  							<li>
  								<a href="#">CSS</a>
  							</li>
  							<li>
  								<a href="#">Tutorials</a>
  							</li>
  						</ul>
  					</div>
  				</div>
  			</div>
  		</div>

  		<!-- Side Widget -->
  		<div class="card my-4">
  			<h5 class="card-header">Side Widget</h5>
  			<div class="card-body">
  				You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
  			</div>
  		</div>

  	</div>

  </div>
  <!-- /.row -->


  <%= link_to "Add Review",  new_review_path %> <br/> 

  <%= link_to "Edit", edit_article_path(@article) %> |
  <%= link_to "Destroy",article_path(@article), method: :delete, data:{confirm: "Are you Sure?"}%> |
  <%= link_to "ALL ", articles_path %>

app/views/categories/_form.html.erb
<%=form_for @category do |f|%>
	<%if @category.errors.any?%>
	<h3>These errors prohibited the form </h3>
	<ul>
		<%@category.errors.full_messages.each do |msg|%>
		<li><%=msg%></li>
		<%end%>
	</ul>
	<%end%>

	<label for= "category_name"> name : </label><br/>
	<%= f.text_field :name %> <br/>
	
    <label for= "category_description "> description  : </label><br/>
	<%= f.text_area :description%> <br/>


	<%= f.submit %>


<%end%>

app/views/categories/edit.html.erb
<h2>EDIT Category</h2>>
<%= render 'form'%>

app/views/categories/index.html.erb
<p><%if @categories.empty?%></p>
<p>NO CATEGORIES FOUND</p>
<%else%>
<p> LISTING CATEGORIES <%= (@categories.length)%></p>

<ol>
		<%@categories.each do |category|%>
		<li>
		
			<%= link_to category.name, category_path(category.id)%> - 
			<%= category.description%>  - 
			(<%= category.articles.length%> article)
			
		</li>
		<%end%>

</ol>


<%end%>
<%= link_to "Add category" , new_category_path%>

app/views/categories/new.html.erb
<h2>ADD Category</h2>
<%= render 'form'%>

app/views/categories/show.html.erb
<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

	          <!-- Title -->
	          <h1 class="mt-4"><%= @category.name %></h1>

	          <!-- Author -->
	          <p class="lead">
	            in 
	            <%= link_to @category.name, @category %>
	          </p>
	           	<hr>

         		 <!-- Post Content -->
         	 		<p> <%= raw(@category.description) %></p>
         		<hr>



          <h1 class="display-5"> Listing Articles
            <small><%= @category.articles.count %></small>
          </h1>


        <% @category.articles.each do |article| %>  	
          <!-- Blog Post -->
	          <div class="card mb-4">
	          	<%= image_tag(article.feature_image_url, size: "750x300", class: "card-img-top") %>
	            <div class="card-body">
	              <h2 class="card-title"><%= article.title %></h2>
	              <p class="card-text"><%= raw(article.body.truncate(250)) %></p>
	              <%= link_to "Read More", article, class: 'btn btn-primary' %> 
	            </div>
	            <div class="card-footer text-muted">
	              Posted on <%= article.publish_date.strftime("%B %d %Y") %>
	             <%= link_to article.category.name, article.category %>
	            </div>
	          </div>
          <% end %>














         		</div>
          
          
         
          <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

         






<h2><%= @category.name%></h2>

<p> Related Topics - <%= @category.description %></p>

<p><%if @category.articles.empty?%></p>
<p>NO ARTICLES FOUND</p>
<%else%>
<h3> LISTING ARTICLES (<%= @category.articles.length%>)</h3>

<ol>
		<%@category.articles.each do |article|%>
		<li>
			<%= image_tag(article.feature_image_url ,size: "80x80" )%>

			<%= link_to article.title, article_path(article.id)%> 
			<%= article.body%> <br/>

			<h4> Is Published - <%= article.is_published%> </h4> <br/>
			<h4> Publish Date : <%= article.publish_date%> </h4> <br/>  
			<h4><%= article.category.name %></h4>
		</li>
		<%end%>

</ol>


<%end%>




<%= link_to "Edit", edit_category_path(@category) %> |
<%= link_to "Destroy",category_path(@category), method: :delete, date:{confirm: "Are you Sure?"}%> |
<%= link_to "ALL ", categories_path %>

app/views/layouts/_nav.html.erb
 <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">MyBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <%= link_to "Articles", articles_path, class: "nav-link" %> 
<!--               <a class="nav-link" href="/articles">Articles</a>
 -->            </li>

           <li class="nav-item dropdown <%= controller.controller_name == 'categories' ? 'active' : ''%>">
        <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <% Category.all.each do |category| %>
           <!-- <a class="dropdown-item" href="#">Action</a> -->
           <%= link_to category.name , category, class: 'dropdown-item' %>
         <% end %>
       </div>
     </li>


            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="mb-4">

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title> 

     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="/javascripts/jquery.js"></script>
    <script src="/javascripts/bootstrap.js"></script>

    <link href="/stylesheets/bootstrap.css" rel="stylesheet" />
    <link href="/stylesheets/blog-home.css" rel="stylesheet" />
  </head>

  <body>

  <%= render '/layouts/nav' %>
 
    <div class="container">
      <%= notice %>
      <%= alert %>

      <%= yield %>
    </div>

     <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>


  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f|%>

<%if @review.errors.any?%>
<h3>These  Errors prohibited review form</h3>

<ul>
		<%@review.errors.full_messages.each do |msg|%>
		<li>
			<%= msg %>
		</li>
		<%end%>
</ul>
<%end%>



<label for= "review_article_id" >  Article Title :</label>
<%= @review.article.title%>


<%= f.hidden_field :article_id, value: @review.article_id %><br/>

<label for = "review_body"> Write a Review: </label><br/>
<%= f.text_area :body %><br/>
<label for ="review_rating"> Rating :</label>
<%= f.radio_button :rating,1%>1
<%= f.radio_button :rating,2%>2
<%= f.radio_button :rating,3%>3
<%= f.radio_button :rating,4%>4
<%= f.radio_button :rating,5%>5 <br/>
<%= f.submit%>
<%end%>

app/views/reviews/edit.html.erb
<h2>Edit review</h2>
<%= render "form"%>

app/views/reviews/index.html.erb
<ol>
<% @reviews.each do |review| %>
	<li>
		<%=  review.body %>
	</li>
<%end%>
</ol>


<%= link_to "Add review ", new_review_path %>

app/views/reviews/show.html.erb
<h2> Article Title : <%= link_to @review.article.title, article_path(@review.article_id) %> </h2> <br/>
<h3><%=@review.body%> - <%=@review.rating%></h3>
<h4>Other review for this Article</h4>
<ol>
<%@review.article.reviews.each do |review|%>
<li>
   	<%=review.body%> - (<%= review.rating%>)
</li>
<%end%>
</ol>